### PR TITLE
Simplify the logical to invalid leader.

### PR DESCRIPTION
**Pull request by Shylock-Hg**

### CODE REVIEW

**Comment by critical27** [comment]
This will fix https://jira.nebula-graph.io/browse/NG-460?

**Comment by Shylock-Hg** [comment]
> This PR will fix https://jira.nebula-graph.io/browse/NG-460?

Not related.

**Review by liuyu85cn — APPROVED** [review]
LGTM

**Review by panda-sheep — APPROVED** [review]
Good！

**Pull request merged**
