### PR TITLE
Fix lookup bug

### PR DESCRIPTION
**Pull request by czpmango**
Fix [https://jira.nebula-graph.io/browse/NG-347](https://jira.nebula-graph.io/browse/NG-347)

This bug is caused by C++ operator?: not returning the appropriate type.

### CODE REVIEW

**Review by jievince — APPROVED** [review]
Well done

**Review by yixinglu — APPROVED** [review]

**Comment by Shylock-Hg** [comment]
Plz add cases to graph

**Comment by bright-starry-sky** [comment]
Good job, thanks for your take this. 
I am in favor of Shylock-Hg's suggestion, need to add some test cases. IIRC,  can not support all of functional expressions.

**Review by bright-starry-sky — APPROVED** [review]
LGTM.

**Pull request merged**
