### PR TITLE
storage client no retry， retry is completely invalid.

### PR DESCRIPTION
**Pull request by panda-sheep**
The current storage client retry mechanism is completely wrong.
For example
1）a host's request contains 2 parts, a part succeeds, the other has leader change,
2）a host's request contains 3 parts, one part is successful, and the other two parts have leader change, and these two parts correspond to two leaders respectivelys.
In two way, how many times the request is retried is always an error. Retrying is completely invalid.

There are two solutions:
1) The storage client does not retry, modify the leader host of all the parts of the leader change, so the next time you re-execute sql, it will succeed
2) Storage client retry. When the errcode in the same request is leader change, it will retry, otherwise it will not retry. Need to reorganize the leader change requst in the same request of collectResponse and getResponse. Then it may be sent multiple times.

The current pr is not to retry for storage client，I prefer storage client not to retry
Please hold this pr first for chaos test

The retry of storage client  pr will also perform the chaos test.

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
Good catch. Maybe we could reorganize the request of  one host as `map<PartID, Request>` in this form it's easy to reform when retry request.

**Comment by panda-sheep** [comment]
> map
shoud map<leaderHost, Request> Both ways are ok, I am testing

**Comment by Shylock-Hg** [comment]
> > map
> > shoud map<leaderHost, Request>
> > Both ways are ok, I am testing

I means map<Host, map<PartID, Request>>

**Comment by panda-sheep** [comment]
> > > map
> > > shoud map<leaderHost, Request>
> > > Both ways are ok, I am testing
> 
> I means map<Host, map<PartID, Request>>

Shouldn't be like this,
The `request `contains the parts contained in the request,  and the redundant part contained in the `request   `should be removed

**Review by critical27 — APPROVED** [review]
LGTM

**Review by CPWstatic — APPROVED** [review]

**Pull request merged**
