### PR TITLE
ignore suggest-override warning in gcc

### PR DESCRIPTION
**Pull request by critical27**
In https://github.com/vesoft-inc/nebula-storage/pull/232 use gmock, however, for now our gtest version is outdated, so we could only use the old style macro, which can not mark override.

We can ignore it by adding `#pragma GCC diagnostic ignored "-Wsuggest-override"`, but we failed to compile in clang for now, this would raise clang `unknown-warning-option` warning.

If we try to `#pragma clang diagnostic ignored "-Wunknown-warning-option"`, gcc can't ignore it anymore.

For similarity, just ignore `suggest-override` in gcc, and we could add it back when third-party update.

### CODE REVIEW

**Review by dutor — COMMENTED** [review]
Better add a TODO comment here. Since we really benefit from this option.

**Comment by critical27** [comment]
> Better add a TODO comment here. Since we really benefit from this option.

👌

**Review by dutor — APPROVED** [review]
LGTM.

**Review by bright-starry-sky — APPROVED** [review]
LGTM

**Review by darionyaphet — APPROVED** [review]

**Pull request merged**
