### PR TITLE
Add time zone field in auth response.

### PR DESCRIPTION
**Pull request by Shylock-Hg**

### CODE REVIEW

**Comment by bright-starry-sky** [comment]
Could you give me some comments? thanks.

**Comment by Shylock-Hg** [comment]
> Could you give me some comments? What is the purpose of this PR? thanks.

Let the client know timezone of cluster.

**Review by laura-ding — APPROVED** [review]

**Review by CPWstatic — APPROVED** [review]

**Comment by whitewum** [comment]
any test case provided? or to reference?

**Comment by Shylock-Hg** [comment]
> any test case provided? or to reference?

This is test and doc in client.

**Pull request merged**
